
services:
  - type: web
    name: telegram-render-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token_here
